caught some exception
should be empty here: 
